### ISSUE TITLE
Problem: Not able to use the rest api

### ISSUE THREAD

**Issue by dpdrmj** [dexter/dexter#21]
I added the maven dependency to my project (in eclipse) but it could not find dexter-client in the repository. Therefore, i am unable to access the rest api using  DexterRestClient. Can anyone help me with this?
I have  a stream of tweets and need to use entity linking with the tweets.

**Comment by diegoceccarelli** [comment]
Dear @dpdrmj, I apologize for the delay of my answer. Could you try to import `dexter-client` package in your pom? you first go into the dexter-client and run 'mvn install', and then add to your pom.xml file the snippet: 

    </dependency>
                <groupId>it.cnr.isti.hpc</groupId>
		        <artifactId>dexter-client</artifactId>
                <version>2.1.1</version>
    </dependency>

.. then refresh your project in eclipse. Let me know if it solved, and sorry again for the delay. 
Diego

**Comment by dpdrmj** [comment]
Thanks a lot for replying. I run the 'mvn install' in dexter-client. I've already added the code snippet in the pom.xml file but eclipse is not recognizing it and giving me error. I don't know what is wrong (apparently i'm noob to this maven dependency thing). Do i need to do something else too?
