### ISSUE TITLE
How to pack the server

### ISSUE THREAD

**Issue by davidTamayo** [dexter/dexter#23]
Hi,
We have extended Dexter to be able to use Spanish Wikipedia. Now, I don’t see how to pack it into a single jar, similar to dexter-2.1.0.jar.

**Comment by diegoceccarelli** [comment]
once that you have the model, you just point at it with the `dexter-conf.xml` file and reuse the original `dexter-2.1.0.jar`, otherwise you can just go into `dexter-webapp`,  edit the `dexter-conf.xml` there and, from `dexter-webapp` run `scripts/run-server.sh`.

**Comment by davidTamayo** [comment]
Thanks! It works.
