### ISSUE TITLE
How to change the port?

### ISSUE THREAD

**Issue by Xiariyouhu** [dexter/dexter#27]
My port 8080 has been used. How to change the listen port?

**Comment by eracle** [comment]
As a workaround you could use:
`sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080`

**Comment by diegoceccarelli** [comment]
you can run dexter adding `-Djetty.port`. 
e.g.: 
`java -Djetty.port=$yourport -jar dexter.jar `
