### ISSUE TITLE
I cant run, ı get bellow error

### ISSUE THREAD

**Issue by mathematiciseverywhere** [dexter/dexter#38]
scripts/create-label2id-file.sh
export titles and redirects from the dump (../enwiki-latest-pages-articles.json)
Error: Could not find or load main class it.cnr.isti.hpc.dexter.cli.label.ExportArticlesIdCLI
sort by id
indexing id -> label
Error: Could not find or load main class it.cnr.isti.hpc.dexter.cli.label.IndexIdToLabelCLI
sort by title
adding redirect
Error: Could not find or load main class it.cnr.isti.hpc.dexter.cli.label.AddRedirectIdCLI
mv: cannot stat 'dataen-model-20180201/tmp/tmp': No such file or directory
sort title and redirect
indexing label -> id
Error: Could not find or load main class it.cnr.isti.hpc.dexter.cli.label.IndexLabelToIdCLI

**Comment by diegoceccarelli** [comment]
Hi, it seems that the script can't find the java classes, can you check that you have the jar in the right place?

**Comment by mathematiciseverywhere** [comment]
hi, diego. Where can I download the jar file?

**Comment by mathematiciseverywhere** [comment]
i read #10 
He say: Step 2.
                      2.0 Downloaded the dexter-master from this github
                      and generate the jarfile : "dexter-core-2.1.0-jar-with-dependencies.jar"

**Comment by mathematiciseverywhere** [comment]
I generate "dexter-core-2.1.0-jar-with-dependencies.jar".
I run 
java -Xmx8000m -Dlogat=1000 -Dlog=INFO -cp ~/Downloads/dexter-master/dexter-core/scripts/target/dexter-core-2.1.0-jar-with-dependencies.jar it.cnr.isti.hpc.dexter.cli.label.ExportArticlesIdCLI -input $WIKI_JSON_DUMP -output

I get this : 
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	The method getInput() is undefined for the type ExportArticlesIdCLI
	The method openOutput() is undefined for the type ExportArticlesIdCLI
	ProgressLogger cannot be resolved to a type
	ProgressLogger cannot be resolved to a type
	RecordReader cannot be resolved to a type
	Article cannot be resolved to a type
	RecordReader cannot be resolved to a type
	Article cannot be resolved to a type
	JsonRecordParser cannot be resolved to a type
	Article cannot be resolved to a type
	Article cannot be resolved to a type
	TypeFilter cannot be resolved to a variable
	RecordParser cannot be resolved to a type
	Article cannot be resolved to a type
	The method closeOutput() is undefined for the type ExportArticlesIdCLI
