### ISSUE TITLE
Dexter download fail

### ISSUE THREAD

**Issue by SMinL** [dexter/dexter#43]
I click the download link "http://dexter.isti.cnr.it/dexter.tar.gz", but it fails, as the following shows. Dose the tool not open to us anymore?

"File Transfer Blocked
Transfer of the file you were trying to download or upload has been blocked in accordance with company policy. Please contact your system administrator if you believe this is in error.

File name: dexter.tar.gz"

**Comment by diegoceccarelli** [comment]
http://hpc.isti.cnr.it/~ceccarelli/dexter2.tar.gz

**Comment by soumyasanyal** [comment]
The above link is not working as well. Is there an alternative link to download dexter?
