### ISSUE TITLE
Dexter download link not working

### ISSUE THREAD

**Issue by soumyasanyal** [dexter/dexter#44]
Hi,

The Dexter download link provided in the github README page seems to be down. Is there any alternative link to download the required files?

**Comment by diegoceccarelli** [comment]
Does this link work? 

http://dexter.isti.cnr.it/dexter.tar.gz

**Comment by soumyasanyal** [comment]
No, it still shows the same error. I've tried on two different networks, same result.

File Transfer Blocked
Transfer of the file you were trying to download or upload has been blocked in accordance with company policy. Please contact your system administrator if you believe this is in error.

**Comment by diegoceccarelli** [comment]
@soumyasanyal I think it is your internet provider that it is blocking your download (maybe because it's a 2G download? )

**Comment by soumyasanyal** [comment]
Not the case. I tried with both personal and institute internet, it doesn't work. Is it possible to share the contents over some public domain (like Google drive)?

**Comment by diegoceccarelli** [comment]
@soumyasanyal can you please try to run:

```
wget http://dexter.isti.cnr.it/dexter.tar.gz
```

from a unix shell and tell me the output?

**Comment by soumyasanyal** [comment]
I'm getting 503 error.
HTTP request sent, awaiting response... 503 Service Unavailable
