### ISSUE TITLE
Meaning of i/o parameters

### ISSUE THREAD

**Issue by piskvorky** [dexter/dexter#6]
The input/output parameters seem to be undocumented (or I couldn't find the documentation).

Could you please clarify the meaning of `wn`, `n`, `format` and `debug` in `annotate`?

And similarly, the meaning of `score`, `commonness` and `linkProbability` in the results? (I assume the `spots` dictionary contains only the final entities, and not all spotted candidates, right?)

Thanks!

**Comment by vmanisha** [comment]
wn : wikiname, n = number of terms in window for term spotting . debug : will output several values of the spotter (probability numbers etc) .. 
commonness : this is how frequently it occurs in corpus
linkProb : probability of text being hyperlinked on wikipedia.

**Comment by piskvorky** [comment]
Thanks!

Do you know why `wn` is an extra parameter? Does `wn=true` have some bad performance implications? Why isn't it always on?

**Comment by vmanisha** [comment]
wn needs another lookup but no it does not affect accuracy alot. I have tested it on few thousand queries. It does them under 20 mins. But on longer text it may be an issue. One note though, if you do not use wikinames, you may have no way of comparing different spots mapping to same article : for example 'new york' and 'ny' are valid spots but wikiname of 'New york' makes it consistent to compare the two. you can always use entity id when name is not important.

**Comment by giacbrd** [comment]
Hi,
you probably already know, but it is possible to retrieve a Wikipedia page
by entity ID, setting the curid parameter in the url.
e.g. http://en.wikipedia.org/?curid=8485 =>
http://en.wikipedia.org/wiki/Diego_Maradona

2015-05-08 17:02 GMT+02:00 vmanisha <notifications@github.com>:

**Comment by diegoceccarelli** [comment]
@piskvorky  you're right, they are not explained, that's bad, we'll fix this issue in the project. Let me resume the meanings: 

  * ``wn=[true|false]``  add the wikinames: entities are represented as
integers, if you want also the real name of the entity add ``wn=true``;
  * ``n=[int]`` max number of entities to return;
  * ``format=[txt|json]`` format of the input, dexter can annotate also
semistructured documents (have a look to MultifieldDocument), if you
want to annotate a multifield document you have to specify format=json
and sent it to dexter encoded in the proper format;
  * ``debug=[true|false]`` if true will add some debug info to the response.

*And similarly, the meaning of score, commonness and linkProbability in the results? (I assume the spots dictionary contains only the final entities, and not all spotted entities, right?)*

  * ``score``  the confidence of the disambiguator in annotating the entity;
  * ``commonness``,``link probability``  are two features commonly used for the disambiguation/spotting, that are good to see (altough we could expose them only in the debug mode...):
    - the ``link probability`` represents the probability for a piece of text to be a link, computed as (frequency of   the piece of text as: frequency as anchor text in wikipedia / frequency of the
piece of text as anchor text or 'raw' text); 
    - the ``commonness`` represents the probability that the spot ``s`` links to the linked entity ``e``,i.e.,  ``p(e|s)`` computed as (frequency of the anchor text targetting to the entity / frequency of the anchor text on wikipedia).

**Comment by piskvorky** [comment]
Thanks @diegoceccarelli !

Also thank you @giacbrd for the `curid` tip -- I actually didn't know :)
